name: Distribute

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build package
        run: uv build

      - name: Create executable
        run: uv run pyinstaller --onefile src/scrapenfill/start.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe